---
collections:
  - ansible.controller
  - ansible.utils
  - ansible.posix
  - awx.awx
  - ansible.netcommon
  - name: servicenow.itsm
    version: 1.4.0
  - name: servicenow.itsm
    version: 2.0.0
