---
- name: Troubleshoot
  hosts: rhel
  gather_facts: true

  tasks:
    - name: dump message
      ansible.builtin.debug:
        var: event

    - name: collect some info
      ansible.builtin.shell: 
        cmd: ps aux | grep docker
      register: ps

    - name: check dns 
      ansible.builtin.shell: 
        cmd: ping -c 5 rhel 
      register: ping

    - name: summary
      ansible.builtin.debug:
        msg:
        - "Running tasks: {{ ps }}"
        - "DNS check: {{ ping }}"

    - name: Create incident
      servicenow.itsm.incident:
        instance:
        state: new
        caller: admin
        short_description: "{{ event.severity }} - {{ event.message }}"
        description: |
          "JHB kiosk application is unreachable."
          "{{ ps }}"
          "{{ ping }}"
        impact: low
        urgency: low
