---
- name: Troubleshoot
  hosts: rhel
  gather_facts: true

  tasks:
    - name: dump message
      ansible.builtin.debug:
        var: event

    - name: collect some info
      ansible.builtin.shell: 
        cmd: ps aux | grep docker
      register: ps

    - name: check dns 
      ansible.builtin.shell: 
        cmd: ping -c 5 rhel 
      register: ping

    - name: summary
      ansible.builtin.debug:
        msg:
        - "Running tasks: {{ ps }}"
        - "DNS check: {{ dig }}"
