---
- name: Troubleshoot
  hosts: localhost
  gather_facts: false

  tasks:
    - name: dump message
      ansible.builtin.debug:
        var: event

    - name: collect some info
      ansible.builtin.command: 
        cmd: ps aux
      register: ps

    - name: check dns 
      ansible.builtin.command: 
        cmd: dig localhost
      register: dig

    - name: summary
      ansible.builtin.debug:
        msg:
        - "Running tasks {{ ps }}"
        - "DNS check {{ dig }}"
