---
version: 3

images:
    base_image:
        name: 'minimal-decision-environment:latest'
dependencies:
    python:
        - aiohttp
        - aiokafka
        - boto
        - boto3
    system:
        - pkgconf-pkg-config [platform:rpm]
        - systemd-devel [platform:rpm]
        - gcc [platform:rpm]
        - python39-devel [platform:rpm]
    galaxy:
        collections:
            - name: ansible.eda
            - name: cloin.eda
            - name: kubealex.eda
            - name: ansible.utils
            - name: community.general
