name: ServiceNow EE build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  EE_NAME: snow12-ee
  EE_FOLDER: servicenow-ee
  REGISTRY_USER: ${{ secrets.REDHAT_USERNAME }}
  REGISTRY_PASS: ${{ secrets.REDHAT_PASSWORD }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-20.04
    steps:
      # In this job, all steps begin with a name
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Log in to quay.io
        id: registry-quay
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASS }}

      - name: Log in to registry.redhat.io
        id: registry-redhat
        uses: redhat-actions/podman-login@v1
        with:
          registry: registry.redhat.io
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASS }}

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
         image: ${{ env.EE_NAME }}
         tags: latest ${{ github.sha }}
         containerfiles: |
           ./${{ env.EE_FOLDER }}/Containerfile
           
      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/acme_corp/
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASS }} 

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
