name: reusable workflow
on:
  workflow_call:
    inputs:
      test:
        description: 'just a test'
        type: string

jobs:

  # This workflow contains a single job called "build"
  test:
    runs-on: ubuntu-latest
    steps:

      - name: dump input `test`
        run: echo ${{ inputs.test }}